import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';

test('real PostgreSQL: tenant isolation, roles, quotas and webhook idempotency',async()=>{
 const db=new PGlite();
 const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222',c='33333333-3333-4333-8333-333333333333',d='44444444-4444-4444-8444-444444444444';
 try{
 await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
 create schema auth; create table auth.users(id uuid primary key,email text);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema public,auth to anon,authenticated,service_role;
 grant execute on function auth.uid() to anon,authenticated,service_role;
 insert into auth.users values('${a}','a@example.com'),('${b}','b@example.com'),('${c}','c@example.com'),('${d}','d@example.com');`);
 await db.exec(await readFile(new URL('../supabase/001_initial.sql',import.meta.url),'utf8'));
 const scalar=async(sql,params=[])=>Object.values((await db.query(sql,params)).rows[0])[0];
 const user=async(id)=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');};
 const service=async()=>db.exec('reset role; set role service_role');
 await user(a);
 const wa=await scalar("select public.create_workspace('Alpha','Services')");
 assert.equal(await scalar('select public.workspace_role($1)',[wa]),'owner');
 await user(b);
 const wb=await scalar("select public.create_workspace('Beta','Retail')");
 assert.equal((await db.query('select * from public.workspaces')).rows.length,1);
 assert.equal(await scalar('select count(*) from public.workspaces where id=$1',[wa]),0);
 assert.equal(await scalar('select public.workspace_role($1)',[wa]),null);
 await assert.rejects(()=>db.query("select public.update_workspace($1,'Hijacked','','')",[wa]),/permisos/);
 await assert.rejects(()=>db.query("update public.workspaces set name='Hijacked' where id=$1",[wb]),/permission denied/);
 await assert.rejects(()=>db.query('select * from public.whatsapp_credentials'),/permission denied/);
 await assert.rejects(()=>db.query('insert into public.platform_admins values($1)',[b]),/permission denied/);
 await assert.rejects(()=>db.query("select public.reserve_message($1,$2,gen_random_uuid(),'525512345678','hack','template')",[wa,a]),/permission denied/);
 await user(a);
 await db.query("select public.manage_member($1,'c@example.com','viewer')",[wa]);
 await db.query("select public.manage_member($1,'d@example.com','agent')",[wa]);
 await assert.rejects(()=>db.query("select public.manage_member($1,'b@example.com','agent')",[wa]),/límite/);
 await user(c);
 assert.equal(await scalar('select count(*) from public.workspaces'),1);
 await assert.rejects(()=>db.query("select public.update_workspace($1,'Hijacked','','')",[wa]),/permisos/);
 await assert.rejects(()=>db.query("select public.manage_member($1,'b@example.com','admin')",[wa]),/permisos/);
 await service();
 await db.query("select public.connect_whatsapp($1,$2,'100001','200001','+52 5512345678','Alpha','cipher')",[wa,a]);
 await assert.rejects(()=>db.query("select public.reserve_message($1,$2,gen_random_uuid(),'525512345678','hi','template')",[wa,c]),/autorizado/);
 await assert.rejects(()=>db.query("select public.reserve_message($1,$2,gen_random_uuid(),'525512345678','hi','text')",[wa,a]),/24 horas/);
 await db.query("select public.record_inbound('wamid.in','100001','200001','525512345678','hello','text',now())");
 await db.query("select public.record_inbound('wamid.in','100001','200001','525512345678','hello','text',now())");
 assert.equal(await scalar("select count(*) from public.messages where provider_id='wamid.in'"),1);
 await db.query("select public.record_inbound('wamid.wrong','100001','999999','525512345678','wrong','text',now())");
 assert.equal(await scalar("select count(*) from public.messages where provider_id='wamid.wrong'"),0);
 const id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
 assert.equal(await scalar("select public.reserve_message($1,$2,$3,'525512345678','reply','text')",[wa,d,id]),true);
 assert.equal(await scalar("select public.reserve_message($1,$2,$3,'525512345678','reply','text')",[wa,d,id]),false);
 await assert.rejects(()=>db.query("select public.reserve_message($1,$2,$3,'525512345678','changed','text')",[wa,d,id]),/ya utilizado/);
 // A delivery webhook can arrive before the sending HTTP request returns.
 await db.query("select public.record_delivery('wamid.out','read',null,'100001','200001')");
 await db.query("select public.finish_message($1,'wamid.out','accepted',null)",[id]);
 await db.query("select public.record_delivery('wamid.out','delivered',null,'100001','200001')");
 assert.equal(await scalar('select status from public.messages where id=$1',[id]),'read');
 await user(b);assert.equal(await scalar('select count(*) from public.messages'),0);
 await user(c);assert.equal(await scalar('select count(*) from public.messages'),2);
 await user(a);assert.equal(await scalar('select public.workspace_usage($1)',[wa]),1);
 await db.exec('reset role');
 await db.query('insert into public.platform_admins values($1)',[b]);
 await user(b);assert.equal(await scalar('select count(*) from public.workspaces'),2);
 const pid=await scalar('select plan_id from public.workspaces where id=$1',[wa]);
 await db.query("select public.save_plan($1,'Inicial',1,3,true,'small')",[pid]);
 await assert.rejects(()=>db.query("select public.save_plan($1,'Inicial',1,2,true,'small')",[pid]),/más usuarios/);
 await service();
 await assert.rejects(()=>db.query("select public.reserve_message($1,$2,gen_random_uuid(),'525512345678','limit','text')",[wa,a]),/límite mensual/);
 await user(b);await db.query("select public.admin_workspace($1,$2,'suspended')",[wa,pid]);
 await user(a);assert.equal(await scalar('select public.workspace_role($1)',[wa]),null);assert.equal(await scalar('select count(*) from public.messages'),0);
 await assert.rejects(()=>db.query('select public.disconnect_whatsapp($1)',[wa]),/autorizado/);
 await service();await assert.rejects(()=>db.query("select public.reserve_message($1,$2,gen_random_uuid(),'525512345678','suspended','text')",[wa,a]),/autorizado/);
 await db.exec('reset role;set role anon');
 await assert.rejects(()=>db.query("select public.create_workspace('No access','')"),/permission denied/);
 }finally{await db.close();}
});
